\documentclass{article}

\begin{document}
\SweaveOpts{concordance=TRUE}

\section{Introduction}
Leslie Lamport is the initial developer of the document preparation system \LaTeX \cite{lamport94}.

% Multiple citation example
%\cite{citation01,citation02,citation03}

\begin{thebibliography}{10}

\bibitem{lamport94}
  Leslie Lamport,
  \textit{\LaTeX: a document preparation system},
  Addison Wesley, Massachusetts,
  2nd edition,
  1994.

\end{thebibliography}

\end{document}
